name: Go

on:
  push:
  pull_request:

env:
  GOLANGCI_LINT_VERSION: v2.12.2

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        skip-cache: true
        version: ${{ env.GOLANGCI_LINT_VERSION }}

    - name: Test
      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
